### ISSUE TITLE
No palette symbol tooltips with 3.3.2 Flatpak

### ISSUE THREAD

**Issue by lpinner** [flathub/org.musescore.MuseScore#42]
Musescore 3.3.2 installed in Ubuntu 18.04 via Flatpak.

When mousing over symbols in the docked palette, tooltips do not appear. They appear for symbols in the master palette and for toolbar buttons.

The tooltips work as expected in the docked palette when I tried the Musescore 3.3.2 AppImage and when I rolled the Flatpak version back to 3.2.3 (via `flatpak update --commit=aa21391f59a8a454b2dad95fe2e195a106a7533f7ed5bbcdcc7259f07dac09a5 org.musescore.MuseScore`)

```
flatpak remote-info --log flathub org.musescore.MuseScore

MuseScore - Create, playback, and print sheet music for free

        ID: org.musescore.MuseScore
       Ref: app/org.musescore.MuseScore/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 3.2.3
   License: GPL-2.0
Collection: org.flathub.Stable
  Download: 67.3 MB
 Installed: 159.3 MB
   Runtime: org.kde.Platform/x86_64/5.12

       Sdk: org.kde.Sdk/x86_64/5.12
    Commit: feac4f6e656f164d1618c72f56d29bb71baa31b9c40215b1afb5b9a527988569
    Parent: aa21391f59a8a454b2dad95fe2e195a106a7533f7ed5bbcdcc7259f07dac09a5
   Subject: Bump MuseScore to 3.3.2 (6e5a7806)
      Date: 2019-11-15 17:00:32 +0000
   History: 

    Commit: aa21391f59a8a454b2dad95fe2e195a106a7533f7ed5bbcdcc7259f07dac09a5
   Subject: Keep X11 default until render bugs are fixed (c17bf42b)
      Date: 2019-08-24 09:34:11 +0000

    Commit: 9bcf9070959711d20df396070d6eb70cf4500fe2d8595439481644a2751bd673
   Subject: Update MuseScore to 3.2.3 (8e66131f)
      Date: 2019-07-12 12:02:38 +0000


```
